# Generated by Django 4.1.3 on 2022-11-10 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv", "xlsx"]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
